### ISSUE TITLE
ROS version

### ISSUE THREAD

**Issue by silviazpi** [astrorick/thesis_work#1]
Hey! I was wondering what ros2 version this code is compatible with. Thank you in advance and congrats for the great work!

**Comment by astrorick** [comment]
This code is designed to work with **ROS2 Humble** but it may work with other distros as well (not tested).

If you have any other question, GitHub issues are not the right tool (unless you find a problem in the code, that is). Write me a private email instead at [me@astrorick.space](mailto:me@astrorick.space). Thanks!
